# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Push Docker image to ACR'
      inputs:
        command: 'push'
        azureSubscriptionEndpoint: 'your-subscription'
        azureContainerRegistry: 'your-container-registry'
        imageName: 'your-registry/repository:$(Build.BuildId)'
        includeLatestTag: true
    
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-cluster-connection'
        namespace: 'dev-test'
        manifests: |
            $(Build.SourcesDirectory)/deploy.yaml