# pipeline-deploy-server-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deploy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-deploy-server
  template:
    metadata:
      labels:
        app: pipeline-deploy-server
    spec:
      containers:
      - name: pipeline-deploy-server-container
        image: as0dev.azurecr.io/kodekloudappcs:$(Build.BuildId)
        ports:
        - containerPort: 80
--- 
# Expose via a Loadbalancer

